//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class aABC
    {
        public aABC()
        {
            this.Abcons = new HashSet<Abcon>();
            this.pdnas = new HashSet<pdna>();
        }
    
        public int ABC { get; set; }
        public string NameABC { get; set; }
        public string NameABCTW { get; set; }
        public string NameABCEng { get; set; }
    
        public virtual ICollection<Abcon> Abcons { get; set; }
        public virtual ICollection<pdna> pdnas { get; set; }
    }
}
