//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abcon
    {
        public string Gsbh { get; set; }
        public string abtype { get; set; }
        public string pdno { get; set; }
        public int Abstep { get; set; }
        public int abps { get; set; }
        public int IDCT { get; set; }
        public string Auditor { get; set; }
        public Nullable<bool> abrult { get; set; }
        public string abmomo { get; set; }
        public string Password2 { get; set; }
        public Nullable<System.DateTime> Userdate { get; set; }
        public Nullable<int> Yn { get; set; }
        public string Maintitle { get; set; }
        public Nullable<int> ABC { get; set; }
        public string from_depart { get; set; }
        public string from_user { get; set; }
        public Nullable<bool> bixoa { get; set; }
        public Nullable<bool> cothutu { get; set; }
        public Nullable<bool> received { get; set; }
        public string ABJOB { get; set; }
        public string Id_VB_CD { get; set; }
        public byte[] signatue { get; set; }
        public Nullable<int> Nhom { get; set; }
        public Nullable<bool> kytoanbo { get; set; }
        public Nullable<int> IDChiTiet { get; set; }
        public Nullable<int> IDCapDuyet { get; set; }
        public Nullable<bool> boqua { get; set; }
        public string lydokhongduyet { get; set; }
        public Nullable<int> ncancel { get; set; }
        public string Donvithongqua { get; set; }
        public string QA { get; set; }
        public string QAmemo { get; set; }
        public string QAmemo2 { get; set; }
    
        public virtual aABC aABC { get; set; }
        public virtual abill abill { get; set; }
        public virtual ABYn ABYn { get; set; }
    }
}
