//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbDepartmentType
    {
        public int DepartmentTypeID { get; set; }
        public string GSBH { get; set; }
        public string DepartmentTypeName { get; set; }
        public string DepartmentTypeNameTW { get; set; }
    }
}
