//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbillCuser
    {
        public string GSBH { get; set; }
        public string abtype { get; set; }
        public string DEPID { get; set; }
        public string isCQ { get; set; }
        public string isAllUser { get; set; }
        public string updateuser { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
        public string YN { get; set; }
    }
}
