//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class abill
    {
        public abill()
        {
            this.Abcons = new HashSet<Abcon>();
            this.pdnas = new HashSet<pdna>();
        }
    
        public string abtype { get; set; }
        public string abname { get; set; }
        public string maintable { get; set; }
        public string abnameTW { get; set; }
        public string abnameEng { get; set; }
    
        public virtual ICollection<Abcon> Abcons { get; set; }
        public virtual abill abill1 { get; set; }
        public virtual abill abill2 { get; set; }
        public virtual ICollection<pdna> pdnas { get; set; }
    }
}
