//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class abill1
    {
        public int Id { get; set; }
        public string abtype { get; set; }
        public string ABDepId { get; set; }
        public string Defuserid { get; set; }
        public string ABJOB { get; set; }
        public int Abstep { get; set; }
        public int Abde { get; set; }
        public string DESC { get; set; }
        public Nullable<bool> bixoa { get; set; }
        public Nullable<int> Nhom { get; set; }
        public Nullable<bool> KyToanBo { get; set; }
    }
}
