//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbNghiPhep
    {
        public int ID { get; set; }
        public string GSBH { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public string IDNguoiDuyet { get; set; }
        public string tennguoiuyquyen { get; set; }
        public string IDNguoiDuocUyQuyen { get; set; }
        public string tennguoithaythe { get; set; }
        public Nullable<int> ThongQua { get; set; }
        public string TenThongQua { get; set; }
    }
}
