//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbNguoiDich
    {
        public string UserID { get; set; }
        public string BADEPID { get; set; }
        public string TenNguoiDich { get; set; }
        public string Email { get; set; }
        public string TenNguoiDichTiengHoa { get; set; }
    }
}
