//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABYn
    {
        public ABYn()
        {
            this.Abcons = new HashSet<Abcon>();
            this.AbTrangThaiDuyets = new HashSet<AbTrangThaiDuyet>();
            this.ChiTietBuocKies = new HashSet<ChiTietBuocKy>();
            this.pdnas = new HashSet<pdna>();
        }
    
        public int Yn { get; set; }
        public string YnName { get; set; }
        public string YnNameTW { get; set; }
    
        public virtual ICollection<Abcon> Abcons { get; set; }
        public virtual ICollection<AbTrangThaiDuyet> AbTrangThaiDuyets { get; set; }
        public virtual ICollection<ChiTietBuocKy> ChiTietBuocKies { get; set; }
        public virtual ICollection<pdna> pdnas { get; set; }
    }
}
