//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDepartment
    {
        public string GSBH { get; set; }
        public string CKBH { get; set; }
        public string ID { get; set; }
        public string DepName { get; set; }
        public string DepName_C { get; set; }
        public string DepMemo { get; set; }
        public Nullable<bool> ProYN { get; set; }
        public Nullable<int> Worker_Qty { get; set; }
        public Nullable<int> NQty { get; set; }
        public Nullable<int> tsQty { get; set; }
        public Nullable<int> H7Qty { get; set; }
        public string UserID { get; set; }
        public System.DateTime UserDate { get; set; }
        public string YN { get; set; }
        public Nullable<bool> PlanYN { get; set; }
        public string GXLB { get; set; }
        public string ULID { get; set; }
        public string EMPSYSID { get; set; }
        public Nullable<bool> useYN { get; set; }
        public string Dclass { get; set; }
        public Nullable<bool> mainyn { get; set; }
        public Nullable<int> STDworkers { get; set; }
        public Nullable<int> PCworkers { get; set; }
        public string Porder1 { get; set; }
        public string ULSEQ { get; set; }
        public string DsDepid { get; set; }
        public string IdUserChuQuan { get; set; }
        public Nullable<int> DepartmentTypeID { get; set; }
        public string CQuserid { get; set; }
        public string CQUserid2 { get; set; }
    }
}
