//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOfSupply
    {
        public int IDOfSupplies { get; set; }
        public string GSBH { get; set; }
        public string pdno { get; set; }
        public string OfSuppliesName { get; set; }
        public string BUnit { get; set; }
        public Nullable<int> BNumber { get; set; }
        public string BCommnent { get; set; }
    }
}
