//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buser
    {
        public string GSBH { get; set; }
        public string USERID { get; set; }
        public string USERNAME { get; set; }
        public string PWD { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> LASTDATETIME { get; set; }
        public string YN { get; set; }
        public string depid { get; set; }
        public string JOB { get; set; }
        public string EMPID { get; set; }
        public string Password2 { get; set; }
        public string BADEPID { get; set; }
        public string IdUserQuanLyTT { get; set; }
        public string USERNAMETW { get; set; }
        public string pwdlevel { get; set; }
    }
}
