//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buser_Securety
    {
        public int IDBaoMat { get; set; }
        public string UserID { get; set; }
        public string MyKey { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
    }
}
