//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietBuocKy
    {
        public string GSBH { get; set; }
        public string pdno { get; set; }
        public int abstep { get; set; }
        public int ABPS { get; set; }
        public int Id { get; set; }
        public Nullable<int> Yn { get; set; }
        public string IdNguoiDuyet { get; set; }
    
        public virtual ABYn ABYn { get; set; }
    }
}
