//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucVu
    {
        public string IDChucVu { get; set; }
        public string TenChucVu { get; set; }
        public string GSBH { get; set; }
        public string TenChucVuTiengHoa { get; set; }
        public Nullable<int> IDCapDuyet { get; set; }
    }
}
