//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class pdna1
    {
        public string GSBH { get; set; }
        public string pdNO { get; set; }
        public string Xh { get; set; }
        public string CLBH { get; set; }
        public string Size { get; set; }
        public string CKBH { get; set; }
        public string ZMLB { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> USPrice { get; set; }
        public Nullable<decimal> USACC { get; set; }
        public Nullable<int> CWHL { get; set; }
        public Nullable<decimal> VNPrice { get; set; }
        public Nullable<long> VNACC { get; set; }
        public string Memo0 { get; set; }
        public string CLmemo { get; set; }
        public string CostID { get; set; }
        public string BJNO { get; set; }
        public Nullable<System.DateTime> YQDate { get; set; }
        public Nullable<System.DateTime> CFMDate { get; set; }
        public Nullable<System.DateTime> USERDATE { get; set; }
        public string USERID { get; set; }
        public string YN { get; set; }
        public Nullable<decimal> CLPrice { get; set; }
        public Nullable<decimal> CLACC { get; set; }
        public string FKZT { get; set; }
        public Nullable<decimal> pdACC { get; set; }
        public Nullable<decimal> VNPpd10 { get; set; }
        public string DDtp { get; set; }
        public string DDBH { get; set; }
        public Nullable<int> cycle { get; set; }
        public string CGNO { get; set; }
        public string ZSBH { get; set; }
    }
}
