//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class pdna
    {
        public pdna()
        {
            this.AbTrangThaiDuyets = new HashSet<AbTrangThaiDuyet>();
        }
    
        public string GSBH { get; set; }
        public string pdno { get; set; }
        public Nullable<System.DateTime> pdDate { get; set; }
        public string pdLX { get; set; }
        public Nullable<System.DateTime> USERDATE { get; set; }
        public string USERID { get; set; }
        public string ZSBH { get; set; }
        public string CFMID1 { get; set; }
        public Nullable<System.DateTime> CFMDate1 { get; set; }
        public string CFMID2 { get; set; }
        public Nullable<System.DateTime> CFMDate2 { get; set; }
        public Nullable<int> YN { get; set; }
        public string SB { get; set; }
        public Nullable<int> PMARK { get; set; }
        public string CFMID0 { get; set; }
        public Nullable<System.DateTime> CFMDate0 { get; set; }
        public string pduser { get; set; }
        public string pddepid { get; set; }
        public string pdyyid { get; set; }
        public string yymemo { get; set; }
        public string shmemo { get; set; }
        public string mytitle { get; set; }
        public string pdmemovn { get; set; }
        public string pdmemoch { get; set; }
        public Nullable<bool> bixoa { get; set; }
        public Nullable<int> LevelDoing { get; set; }
        public Nullable<int> ABC { get; set; }
        public string NoiDungDich { get; set; }
        public Nullable<bool> trangthaidich { get; set; }
        public string IdnguoiDich { get; set; }
        public string Abtype { get; set; }
        public Nullable<System.DateTime> CFMDate4 { get; set; }
        public Nullable<bool> dagui { get; set; }
        public string oldpdno { get; set; }
        public string UseIntent { get; set; }
        public string pdnsubject { get; set; }
        public string pdmemovn1 { get; set; }
        public Nullable<bool> isPause { get; set; }
    
        public virtual aABC aABC { get; set; }
        public virtual abill abill { get; set; }
        public virtual ICollection<AbTrangThaiDuyet> AbTrangThaiDuyets { get; set; }
        public virtual ABYn ABYn { get; set; }
        public virtual pdna pdna1 { get; set; }
        public virtual pdna pdna2 { get; set; }
    }
}
