//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDNLink
    {
        public string Gsbh { get; set; }
        public string pdno { get; set; }
        public int ID { get; set; }
        public string Filename { get; set; }
        public string FilePath { get; set; }
        public Nullable<bool> Cancel { get; set; }
    }
}
