//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projectu
    {
        public string GSBH { get; set; }
        public string Jsysid { get; set; }
        public string Jsubid { get; set; }
        public string Jodid { get; set; }
        public string Juserid { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> userdate { get; set; }
        public string yn { get; set; }
        public Nullable<System.DateTime> juadate { get; set; }
        public string juamemo { get; set; }
    }
}
