//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public string gsbh { get; set; }
        public string jsysid { get; set; }
        public string jsubid { get; set; }
        public string jobid { get; set; }
        public string ticketid { get; set; }
        public string jobname { get; set; }
        public string jobmemo { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> userdate { get; set; }
        public string yn { get; set; }
        public string Jleaderid { get; set; }
        public Nullable<System.DateTime> edates { get; set; }
        public Nullable<System.DateTime> edatee { get; set; }
        public Nullable<decimal> jpercent { get; set; }
        public string PDNO { get; set; }
        public string jobnamevn { get; set; }
        public string jobmemovn { get; set; }
        public string Linkfile { get; set; }
        public string Linkfile2 { get; set; }
        public string Linkfile3 { get; set; }
        public Nullable<bool> Share { get; set; }
    }
}
