//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projectm
    {
        public string gsbh { get; set; }
        public string jsysid { get; set; }
        public string sysname { get; set; }
        public string sysmemo { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> userdate { get; set; }
        public string yn { get; set; }
        public string sLeaderid { get; set; }
        public Nullable<System.DateTime> edates { get; set; }
        public Nullable<System.DateTime> edatee { get; set; }
        public Nullable<decimal> Spercent { get; set; }
        public string sysnamevn { get; set; }
        public string sysmemovn { get; set; }
        public string LinkFile { get; set; }
        public string LinkFile2 { get; set; }
        public string LinkFile3 { get; set; }
        public Nullable<bool> Share { get; set; }
    }
}
