//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSwork
    {
        public string GSBH { get; set; }
        public string userid { get; set; }
        public System.DateTime pdates { get; set; }
        public string id { get; set; }
        public string xh { get; set; }
        public string PSmemo { get; set; }
        public string pslink { get; set; }
        public Nullable<System.DateTime> userdate { get; set; }
        public string yn { get; set; }
        public string pslink2 { get; set; }
        public string pslink3 { get; set; }
    }
}
