//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyTrinhXetDuyet
    {
        public string GSBH { get; set; }
        public string abtype { get; set; }
        public string BADEPID { get; set; }
        public int ABstep { get; set; }
        public int ABPS { get; set; }
        public int IDQuyTrinh { get; set; }
        public string NguoiDuyet { get; set; }
        public string USERNAME { get; set; }
        public string IDChucVu { get; set; }
        public string TenChucVuTiengHoa { get; set; }
        public string abtypenameTW { get; set; }
        public string tendonviTW { get; set; }
        public string DonViThongQua { get; set; }
        public string tendonvithongqua { get; set; }
        public Nullable<int> IDLoaiDonVi { get; set; }
        public string DepartmentTypeNameTW { get; set; }
        public Nullable<int> IDCapDuyet { get; set; }
    }
}
