//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ugroup
    {
        public string GSBh { get; set; }
        public string userid { get; set; }
        public string ugno { get; set; }
        public string userid2 { get; set; }
        public string UGtitle { get; set; }
        public string UGmemo { get; set; }
        public Nullable<System.DateTime> userdate { get; set; }
        public string yn { get; set; }
    }
}
