//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class UShare
    {
        public string GSBH { get; set; }
        public string Userid { get; set; }
        public string USID { get; set; }
        public string UGno { get; set; }
        public string UStitle { get; set; }
        public string USmemo { get; set; }
        public string LinkFile { get; set; }
        public Nullable<System.DateTime> sdate { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public Nullable<System.DateTime> userdate { get; set; }
        public string yn { get; set; }
        public string LinkFile2 { get; set; }
        public string LinkFile3 { get; set; }
    }
}
