//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class zszl
    {
        public string zsdh { get; set; }
        public string zsqm { get; set; }
        public string zsjc { get; set; }
        public string zsywjc { get; set; }
        public string tybh { get; set; }
        public string fpdz { get; set; }
        public string yjdz { get; set; }
        public string dh { get; set; }
        public string cz { get; set; }
        public string fzr { get; set; }
        public string bb { get; set; }
        public string llr2 { get; set; }
        public string llr { get; set; }
        public string dybh { get; set; }
        public string mark { get; set; }
        public string USERID { get; set; }
        public Nullable<System.DateTime> USERDATE { get; set; }
        public string TYJH { get; set; }
        public string YN { get; set; }
        public string country { get; set; }
        public string MZsdh { get; set; }
        public string Style { get; set; }
        public Nullable<int> Shippingleadtime { get; set; }
        public Nullable<int> Shippingleadtimes { get; set; }
        public Nullable<int> Customclearanceday { get; set; }
        public string Samplepurchaser { get; set; }
        public string Prodpurchaser { get; set; }
        public string Groupname { get; set; }
        public string Zsdh_TW { get; set; }
        public string Sample_void { get; set; }
        public string TRANDATE { get; set; }
        public string fktj { get; set; }
        public Nullable<decimal> fktj1 { get; set; }
        public string scd { get; set; }
        public string fzr_mail { get; set; }
        public string llr2_mail { get; set; }
        public string llr_mail { get; set; }
        public string pass0 { get; set; }
        public string pass1 { get; set; }
        public string pass2 { get; set; }
    }
}
